### ISSUE TITLE
Prompt for another response

### ISSUE THREAD

**Issue by fritz-fritz** [ZaidElkurdi/AssistantPlus#3]
Do you have any method to prompt for further input? For example if i choose to send a text or create a reminder with Siri, I get prompted to say what i would like it to be. I would love to have similar functionality for a plugin I am developing. Do you see this being a possibility?

What I would want is a way to prompt the user and return the tokens.

**Comment by SalmanBurhan** [comment]
I would like to second this. I am in need for this feature.

**Comment by joemerlino** [comment]
Third this. And the other issue I opened.

**Comment by ZaidElkurdi** [comment]
Delivered in 1.2.0, should be on Cydia tomorrow

**Comment by fritz-fritz** [comment]
Awesome! Thanks for supporting this!
