### ISSUE TITLE
Multi Level commands?

### ISSUE THREAD

**Issue by JulianHH** [ZaidElkurdi/AssistantPlus#5]
Hi there!

A suggestion:
It would be great if you'd support multi level commands, as Illustrated with siris mail feature below:

I ask: write an eMail to bla 
Siri responds: What do you want me to write?
I respond with the text 
Siri asks: do you want me to send it?
I say yes and the eMail will be sent.

Thanks! :)

Best,
Julian

**Comment by ZaidElkurdi** [comment]
You Cana casually already do this as of 1.2 by using listenAfterSpeaking. Check out the inquisitiveSiri example in this repo.

**Comment by JulianHH** [comment]
Thanks! :)

And what about implementing it into Your Assistant+ gui?

**Comment by fritz-fritz** [comment]
@JulianHH There is no way to easily support that in the Assistant+ app. It is much easier to just implement it yourself as a plugin. Good luck!
